[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmd = "npm ci --only=production"

[phases.build]
cmd = "npm run build"

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "3000"