[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "pkg-config"]

[phases.install]
cmd = "cd backend && python -m pip install --no-cache-dir -r requirements.txt"

[phases.build]
cmd = "echo 'Python FastAPI build completed'"

[start]
cmd = "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app/backend"
PYTHONUNBUFFERED = "1"
PORT = "8000"
