# Fixed nixpacks configuration for Railway deployment - Combine install and build phases
[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "pkg-config"]

[phases.build]
cmd = "cd backend && echo 'Starting pip install...' && python -m pip install --no-cache-dir -r requirements.txt && echo 'Pip install completed' && python -m pip list | grep uvicorn && echo 'Build phase completed'"

[start]
cmd = "cd backend && /root/.nix-profile/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app/backend"
PYTHONUNBUFFERED = "1"
PORT = "8000"
