# Fixed nixpacks configuration for Railway deployment - Use consistent python environment
[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "pkg-config"]

[phases.install]
cmd = "cd backend && echo 'Starting pip install...' && /root/.nix-profile/bin/python -m pip install --no-cache-dir -r requirements.txt && echo 'Pip install completed' && /root/.nix-profile/bin/python -m pip list | grep uvicorn && echo 'Install phase completed'"

[start]
cmd = "cd backend && /root/.nix-profile/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app/backend"
PYTHONUNBUFFERED = "1"
PORT = "8000"
