[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmd = "pip install -r requirements.txt"

[phases.build]
cmd = "echo 'Build completed'"

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app"
UVICORN_HOST = "0.0.0.0"
PORT = "8000"