[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "pkg-config"]

[phases.install]
cmd = "pip install --user --no-cache-dir -r requirements.txt"

[phases.build]
cmd = "echo 'Python FastAPI build completed'"

[start]
cmd = "/root/.local/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PORT = "8000"
PATH = "/root/.local/bin:/usr/local/bin:/usr/bin:/bin"