[phases.setup]
nixPkgs = ["python311", "pip", "gcc", "pkg-config"]

[phases.install]
cmd = "pip install --no-cache-dir -r requirements.txt"

[phases.build]
cmd = "echo 'Python FastAPI build completed'"

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PORT = "8000"