# Railway项目配置
# AI Education Platform Backend

[build]
nixpacks = true

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"
HOST = "0.0.0.0"
PORT = "$PORT"

[environments.production.plugins]
# PostgreSQL数据库
postgresql = {}
# Redis缓存  
redis = {}

[environments.production.services]
# 后端API服务
backend = { startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT" }